language: java
jdk: oraclejdk8

cache:
  directories:
  - $HOME/.m2

sudo: false # faster builds

after_success:
- bash <(curl -s https://codecov.io/bash)

notifications:
  slack: martinsteam-group:zt14aQJUuQBNL8TFGM8ss1w0